trainer: hepcnn
output_dir: $SCRATCH/hep-cnn-pytorch

data_config:
    name: hep_images
    train_file: /global/cscratch1/sd/sfarrell/atlas-rpv-images/train.h5
    valid_file: /global/cscratch1/sd/sfarrell/atlas-rpv-images/val.h5
    #test_file: /global/cscratch1/sd/sfarrell/atlas-rpv-images/test.h5
    n_train: 32768 #409600 #412416
    n_valid: 32768
    #n_test: 1024

model_config:
    input_shape: [1, 64, 64]
    conv_sizes: [16, 32, 64]
    dense_sizes: [128]
    optimizer: Adam
    learning_rate: 0.001
    dropout: 0.2

train_config:
    batch_size: 128
    n_epochs: 2
